os: linux
dist: trusty
sudo: required
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - g++-7
      - clang-6.0
      - cmake
      - libc++-dev
      - libc++abi-dev

matrix:
  include:
    - compiler: clang
      env: BUILD_TYPE=Debug

    - compiler: clang
      env: BUILD_TYPE=Release

install:
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi


script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TEST=ON -DBUILD_EXAMPLE=ON .. && make -j
  - ./bin/bitop_test
  - ./bin/table_test
  - ./bin/crc_lut_test
  - ./bin/crc_naive_test
  - ./bin/ccrc_example -f ../example/test_data.bin
  - ./bin/ccrc_example -i "hello world"


