dist: trusty
sudo: required
language:
  - cpp
compiler:
  - clang
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - clang-3.5
      - cmake
script:
  - mkdir build && cd build
  - cmake ..
  - make
