os: linux
dist: trusty
sudo: required
language: cpp

matrix:
  include:
# Clang Configuration
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - cmake
            - libc++-dev
            - libc++abi-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0" BUILD_TYPE=Debug

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
          packages:
            - clang-6.0
            - cmake
            - libc++-dev
            - libc++abi-dev
      env:
        - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0" BUILD_TYPE=Release

    - compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" BUILD_TYPE=Debug

    - compiler: g++
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7" BUILD_TYPE=Release

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo pip install conan
    - conan remote add conan-mpusz https://api.bintray.com/conan/mpusz/conan-mpusz
    - conan user

install:

script:
  - mkdir build && cd build
  - conan install ..
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_TEST=ON .. && make
  - ./bin/crc_test
